go top
eject
?
?
?
?
?
?
? 'Age & Race/Ethnicity'
?
? 'Age & Race/Ethnicity              Under 18  18-35  36-59  60 and Over';
+ '  Total'
locate for race='A'
? 'Asian / Pacific Islander        ' + str(zero,10) + str(eighteen,7);
                                     + str(thirtysix,7) + str(sixty,13);
                                     + str(zero+eighteen+thirtysix+sixty,7)
locate for race='B'
? 'Black                           ' + str(zero,10) + str(eighteen,7);
                                     + str(thirtysix,7) + str(sixty,13);
                                     + str(zero+eighteen+thirtysix+sixty,7)
locate for race='H'
? 'Hispanic                        ' + str(zero,10) + str(eighteen,7);
                                     + str(thirtysix,7) + str(sixty,13);
                                     + str(zero+eighteen+thirtysix+sixty,7)
locate for race='N'
? 'Native American                 ' + str(zero,10) + str(eighteen,7);
                                     + str(thirtysix,7) + str(sixty,13);
                                     + str(zero+eighteen+thirtysix+sixty,7)
locate for race='O'
? 'Other                           ' + str(zero,10) + str(eighteen,7);
                                     + str(thirtysix,7) + str(sixty,13);
                                     + str(zero+eighteen+thirtysix+sixty,7)
locate for race='W'
? 'White                           ' + str(zero,10) + str(eighteen,7);
                                     + str(thirtysix,7) + str(sixty,13);
                                     + str(zero+eighteen+thirtysix+sixty,7)
